from django.urls import path

from planner.views import (index,
                           InmatesListView,
                           InmatesDetailView,
                           UserSettingsView,
                           ContactMessageView,
                           OperationsListView,
                           OperationsCreateView,
                           OperationsDeleteView,
                           OperationsUpdateView,
                           InmateCreateView,
                           DashboardView,
                           FamilyUpdateView,
                           MessagesListView,
                           MessageDetailView,
                           MessagesDeleteView,
                           SavingsDebtsListView,
                           SavingsCreateView,
                           SavingsDeleteView,
                           SavingsUpdateView,
                           DebtsCreateView,
                           DebtsDeleteView,
                           DebtsUpdateView,
                           PortfoliosListView,
                           PortfoliosCreateView,
                           PortfoliosDeleteView,
                           PortfoliosUpdateView,
                           InstrumentCreateView,
                           InstrumentUpdateView,
                           InstrumentDeleteView)

urlpatterns = [
    path("", index, name="index"),
    path("inmates/", InmatesListView.as_view(), name="inmates_list"),
    path("inmates/<int:pk>", InmatesDetailView.as_view(),
         name="inmates_detail"),
    path("inmates/create/", InmateCreateView.as_view(),
         name="inmate-create"),

    path("settings/", UserSettingsView.as_view(), name="user_settings"),
    path("contact/", ContactMessageView.as_view(), name="contact"),

    path("messages/", MessagesListView.as_view(), name="messages_list"),
    path("messages/<int:pk>",
         MessageDetailView.as_view(), name="message_detail"),
    path("messages/<int:pk>/delete/",
         MessagesDeleteView.as_view(), name="message_delete"),

    path("operations/",
         OperationsListView.as_view(), name="operations"),
    path("operations/create/",
         OperationsCreateView.as_view(), name="operations_create"),
    path("operations/<int:pk>/delete/",
         OperationsDeleteView.as_view(), name="operations_delete"),
    path("operations/<int:pk>/update/",
         OperationsUpdateView.as_view(), name="operations_update"),

    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("family/<int:pk>/update/",
         FamilyUpdateView.as_view(), name="family_update"),

    path("savings_and_debts/",
         SavingsDebtsListView.as_view(), name="savings_and_debts"),
    path("savings/create/",
         SavingsCreateView.as_view(), name="savings_create"),
    path("savings/<int:pk>/delete/",
         SavingsDeleteView.as_view(), name="savings_delete"),
    path("savings/<int:pk>/update/",
         SavingsUpdateView.as_view(), name="savings_update"),
    path("debts/create/",
         DebtsCreateView.as_view(), name="debts_create"),
    path("debt/<int:pk>/delete/",
         DebtsDeleteView.as_view(), name="debt_delete"),
    path("debt/<int:pk>/update/",
         DebtsUpdateView.as_view(), name="debt_update"),

    path("portfolios/", PortfoliosListView.as_view(),
         name="portfolios_list"),
    path("portfolios/create/", PortfoliosCreateView.as_view(),
         name="portfolios_create"),
    path("portfolios/<int:pk>/delete/", PortfoliosDeleteView.as_view(),
         name="portfolios_delete"),
    path("portfolios/<int:pk>/update/", PortfoliosUpdateView.as_view(),
         name="portfolios_update"),
    path("instrument/create/", InstrumentCreateView.as_view(),
         name="instrument_create"),
    path("instrument/<int:pk>/update/", InstrumentUpdateView.as_view(),
         name="instrument_update"),
    path("instrument/<int:pk>/delete/", InstrumentDeleteView.as_view(),
         name="instrument_delete"),
]

app_name = "planner"
