# Generated by Django 5.2.5 on 2025-08-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_family_customuser_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='owner',
        ),
        migrations.AddField(
            model_name='budget',
            name='family',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='planner.family'),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balances', to='planner.portfolio')),
            ],
        ),
    ]
