# Generated by Django 5.2.5 on 2025-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
