# Generated by Django 5.2.5 on 2025-08-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_debt_date_savings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
