# Generated by Django 5.2.5 on 2025-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_debt_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
